[SERVICE]
    Flush         2
    Log_Level     warn
    Parsers_File  /fluent-bit/etc/blindway-parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/blindway/application.json
    Parser            blindway_json
    Tag               blindway.backend
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[FILTER]
    Name    lua
    Match   blindway.backend
    script  /fluent-bit/etc/filter-archive-log.lua
    call    archive_log

[OUTPUT]
    Name        kafka
    Match       blindway.backend
    Brokers     kafka-1:19092,kafka-2:19092,kafka-3:19092
    Topics      blindway.application.logs.v1
    Format      json
    Timestamp_Key occurredAt
    Timestamp_Format iso8601
    Retry_Limit 10
